from pickle import TRUE


MODELNAME = "models/feature_box.h5"
RESET = True
TRAIN_COIN_HEAVEN = True
ROTATION_ENABLED = False

REDUCED_FEATURE_SHAPE = (7, 7, 8 if not TRAIN_COIN_HEAVEN else 6) #(17, 17, 8)
FEATURE_SHAPE = (17,17,8)

TRANSITION_HISTORY_SIZE = 20000  # keep only ... last transitions
MIN_TRANSITIONS_SIZE = 1000
SMALLBATCH_SIZE = 64
UPDATE_TARGET = 5
Q_RATE = 0.99
EPSILON_START = 0.1
EPSILON_DECAY = 0.9995
MIN_EPSILON = 0.001
RHO_PLAY = 0.1


TIMING_FEATURES = False
TIMING_PREDICT = True
TIMING_TRAIN = True