MODELNAME = "models/weights.pt"
RESET = False
FEATURE_SHAPE = (17, 17, 8)
TRANSITION_HISTORY_SIZE = 20000  # keep only ... last transitions
MIN_TRANSITIONS_SIZE = 1000
SMALLBATCH_SIZE = 64
UPDATE_TARGET = 5
Q_RATE = 0.99
EPSILON_START = 0.2

ROTATION_ENABLED = False

TIMING_FEATURES = False
TIMING_PREDICT = False
TIMING_TRAIN = True